[package]
name = "manifest"
version = "1.1.1"
description = "An instant grid-based pinboard for note taking."
authors = ["Stephen McGurrin"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "manifest_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
serde_json = "1"
tauri-plugin-dialog = "2.0.0-rc.8"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
